package webtest

type handle int

const (
	DEFAULT handle = iota
	SOFT
	STRICT
)

// WebClientOptions
/*
WebClientOptions allows the customization of behavior for a
WebClient instance. Current options include log path and error
handling options
	- WriteToFile signals if the logs generated by a WebClient instance
		should be written to a file. Default value is false
	- FilePath specifies the file directory and file name the logs will be written to.
		If WriteToFile is set to true, but no FilePath value is explicitly assigned,
		the WebClient will create a file with the naming format ./2006-01-02T15:04:05Z07:00.log
		using the RFC3339 format.
	- HandleError specifies how a WebClient instance should behave when handling errors of any
		kind that arise from any WebClient function.

*/
type WebClientOptions struct {
	WriteToFile bool   `json:"writeToFile"`
	FilePath    string `json:"filePath"`

	/*
		HandleError specifies how a WebClient instance should behave when handling errors of any
		kind that arise from any WebClient function. Current values include:
			- DEFAULT - the default value for error handling which only serves back both responses
				and errors from the HTTP request.
			- SOFT - does not return any errors. Any errors that occur when making an HTTP request
				will be printed by the WebClient instance. There is no guarantee that errors will be
				properly handled behind the scenes or that no errors will be returned back to the user.
			- STRICT - returns all errors that are encountered in any function of a WebClient instance
				and returns them to the user.
	*/
	HandleError handle `json:"handleError"`
}
