package webtest

// WebClientOptions
/*
WebClientOptions allows the customization of behavior for a
WebClient instance. Current options include logging
configuration.
	- WriteToFile signals if the logs generated by a WebClient instance
		should be written to a file. Default value is false
	- FilePath specifies the file directory and file name the logs will be written to.
		If WriteToFile is set to true, but no FilePath value is explicitly assigned,
		the WebClient will create a file with the naming format ./YYYYMMDDThhmmssZ.log
		using a Windows-safe UTC timestamp format.
*/
type WebClientOptions struct {
	WriteToFile   bool   `json:"writeToFile"`
	FilePath      string `json:"filePath"`
	WriteHeaders  bool   `json:"writeHeaders"`
	WriteRequest  bool   `json:"writeRequest"`
	WriteResponse bool   `json:"writeResponse"`
	LogMetadata   bool   `json:"logMetadata"`
}
